services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  bot:
    build: .
    env_file: .env
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build: .
    env_file: .env
    command: ["python", "app/worker.py"]
    depends_on:
      - redis
    restart: unless-stopped
